/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.text_rpg;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

/**
 *
 * @author Xeb
 */
public class battle extends javax.swing.JFrame {

    int turn = 0; //0 - choosing 1: atk warrior 2: atk dragon
    int damage, health;
    boolean isGameOver = false;
    private Timer battleTimer;
    private int delay = 2000; // Adjust delay as needed
    String[] information = new String[3];
    String[] informationHeader = new String[3];
    dragonClass dragon;
    warriorClass warrior;
    
    /**
     * Creates new form battle
     */
    public battle() {
        initComponents();
        quitBtn.setVisible(false);
        quitBtn2.setVisible(false);
        battleAgain.setVisible(false);
        dragon = new dragonClass();
        warrior = new warriorClass();
        
        updateLabel();
        setupBattle();
    }
    void updateLabel()
    {
        information[0] = "Choose your weapon...";
        information[1] = "You attacked Dragon for " + damage + " damage.\n"
        + "Enemy has " + health + " health remaining.";
        information[2] = "The Dragon attacked you for " + damage + " damage.\n"
        + "You have " + health + " health remaining.";
    
        informationHeader[0] = "YOUR TURN!!";
        informationHeader[1] = "YOUR TURN!!";
        informationHeader[2] = "DRAGON TURN";
    }
    private void setupBattle() {
        battleTimer = new Timer(delay, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                performTurn();
            }
        });
        battleTimer.start();
        
        
        arrowBtn.setVisible(true);
        swordBtn.setVisible(true);
        infoLbl.setText(information[turn]);
        turnLbl.setText(informationHeader[turn]);
    }
    
    private void performTurn()
    {
        if(!isGameOver)
        {
            if(turn == 0)
            {
                arrowBtn.setVisible(true);
                swordBtn.setVisible(true);
                updateLabel();
                infoLbl.setText(information[turn]);
                turnLbl.setText(informationHeader[turn]);
            }
            else if(turn == 1)
            {
                health = dragon.getHealth();
                dragonHP.setText("HEALTH: " + health);
                arrowBtn.setVisible(false);
                swordBtn.setVisible(false);
                updateLabel();
                infoLbl.setText(information[turn]);
                turnLbl.setText(informationHeader[turn]);
                turn++;
            }
            else if(turn == 2)
            {
                damage = 20;
                warrior.damageWarrior(damage);
                health = warrior.getHealth();
                warriorHP.setText("HEALTH: " + health);
                arrowBtn.setVisible(false);
                swordBtn.setVisible(false);
                updateLabel();
                infoLbl.setText(information[turn]);
                turnLbl.setText(informationHeader[turn]);
                turn = 0;
            }
            
            if (dragon.isDead() || warrior.isDead()) {
                battleTimer.stop();
                
                //lose
                if(warrior.getHealth() <= 0)
                {
                    turnLbl.setText("YOU LOSE!");
                    infoLbl.setText("<html>Regrettably, the dragon has proven too formidable, and victory eludes you. The"
                            + " kingdom remains imperiledm and the curse persists. We appreciate your valiant effortsm warriorm though "
                            + "fortune did not favor us this time.</html>");
                    quitBtn2.setVisible(true);
                    battleAgain.setVisible(true);
                }
                else if(dragon.getHealth() <= 0)
                {
                    turnLbl.setText("YOU WIN!!");
                    infoLbl.setText("<html>Congratualtion! You have defeated the dragon. You saved the kingdom,"
                            + " and now the curse will be broken! Thank you so much, warrior; you are a hero!</html>");
                    quitBtn.setVisible(true);
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        turnLbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        infoLbl = new javax.swing.JLabel();
        quitBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        swordBtn = new javax.swing.JButton();
        arrowBtn = new javax.swing.JButton();
        dragonHP = new javax.swing.JLabel();
        warriorHP = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        battleAgain = new javax.swing.JButton();
        quitBtn2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        turnLbl.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        turnLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        turnLbl.setText("TURN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(turnLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(turnLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        infoLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        infoLbl.setForeground(new java.awt.Color(51, 51, 51));
        infoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoLbl.setText("test");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(infoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(infoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        quitBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        quitBtn.setText("QUIT");
        quitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitBtnActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("WARRIOR");

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Verdana", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("VS");

        swordBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        swordBtn.setText("SWORD");
        swordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swordBtnActionPerformed(evt);
            }
        });

        arrowBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        arrowBtn.setText("ARROW");
        arrowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrowBtnActionPerformed(evt);
            }
        });

        dragonHP.setBackground(new java.awt.Color(51, 51, 51));
        dragonHP.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        dragonHP.setForeground(new java.awt.Color(51, 51, 51));
        dragonHP.setText("HEALTH: 100");

        warriorHP.setBackground(new java.awt.Color(51, 51, 51));
        warriorHP.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        warriorHP.setForeground(new java.awt.Color(51, 51, 51));
        warriorHP.setText("HEALTH: 100");

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("DRAGON");

        battleAgain.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        battleAgain.setText("BATTLE AGAIN");
        battleAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                battleAgainActionPerformed(evt);
            }
        });

        quitBtn2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        quitBtn2.setText("QUIT");
        quitBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(warriorHP, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2)
                                        .addGap(52, 52, 52)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dragonHP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(arrowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(swordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(battleAgain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quitBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dragonHP, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(warriorHP, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(swordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arrowBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quitBtn2)
                    .addComponent(battleAgain))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitBtnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_quitBtnActionPerformed
    
    private void swordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_swordBtnActionPerformed
        damage = 25;
        dragon.damageDragon(damage);
        turn++;
    }//GEN-LAST:event_swordBtnActionPerformed

    private void arrowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrowBtnActionPerformed
        damage = 20;
        dragon.damageDragon(damage);
        turn++;
    }//GEN-LAST:event_arrowBtnActionPerformed

    private void battleAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_battleAgainActionPerformed
        battle bat = new battle();
        this.setVisible(false);
        bat.setVisible(true);
    }//GEN-LAST:event_battleAgainActionPerformed

    private void quitBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitBtn2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_quitBtn2ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(battle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(battle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(battle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(battle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new battle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arrowBtn;
    private javax.swing.JButton battleAgain;
    private javax.swing.JLabel dragonHP;
    private javax.swing.JLabel infoLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton quitBtn;
    private javax.swing.JButton quitBtn2;
    private javax.swing.JButton swordBtn;
    private javax.swing.JLabel turnLbl;
    private javax.swing.JLabel warriorHP;
    // End of variables declaration//GEN-END:variables
}
